#!/bin/bash

REGISTRY="linuxfacilito.online:5043"
IMAGE=$(cat ~/.auth|sed -n '1p')
PASS=$(cat ~/.auth|sed -n '2p')
BUILD_TAG=$(cat ~/.auth|sed -n '3p')

echo $PASS $REGISTRY $IMAGE
docker login -u ricardo -p $PASS $REGISTRY
docker run --rm $REGISTRY/$IMAGE:$BUILD_TAG java -jar /app/app.jar